module axi_dmac_wrap #(
    parameter bit ILA_EN        = 0,
    parameter bit ASYNC_MODE_EN = 1
) (
    output logic s2mm_irq_o,
    output logic mm2s_irq_o,

    axil_if.slave s2mm_axil,
    axil_if.slave mm2s_axil,

    axis_if.slave  s2mm_axis,
    axis_if.master mm2s_axis,

    axi_if.master s2mm_axi,
    axi_if.master mm2s_axi
);

    axi_dmac #(
        .ID                     (0),
        .SYNC_TRANSFER_START    (0),
        .CYCLIC                 (0),
        .MAX_BYTES_PER_BURST    (128),
        .FIFO_SIZE              (8),
        .DISABLE_DEBUG_REGISTERS(0),
        .ENABLE_DIAGNOSTICS_IF  (0),
        .ALLOW_ASYM_MEM         (0),
        .CACHE_COHERENT_DEST    (0),

        .DMA_DATA_WIDTH_SRC   (s2mm_axi.DATA_WIDTH),
        .DMA_DATA_WIDTH_DEST  (s2mm_axi.DATA_WIDTH),
        .DMA_LENGTH_WIDTH     (24),
        .DMA_2D_TRANSFER      (0),
        .DMA_AXI_PROTOCOL_DEST(1),
        .DMA_AXI_PROTOCOL_SRC (1),
        .DMA_TYPE_DEST        (1),
        .DMA_TYPE_SRC         (1),
        .DMA_AXI_ADDR_WIDTH   (s2mm_axi.ADDR_WIDTH),
        .DMA_AXIS_ID_W        (s2mm_axis.ID_WIDTH),
        .DMA_AXIS_DEST_W      (s2mm_axis.DEST_WIDTH),

        .ASYNC_CLK_REQ_SRC (ASYNC_MODE_EN),
        .ASYNC_CLK_SRC_DEST(ASYNC_MODE_EN),
        .ASYNC_CLK_DEST_REQ(0),

        .AXI_SLICE_DEST   (0),
        .AXI_SLICE_SRC    (0),
        .AXI_ID_WIDTH_SRC (s2mm_axi.ID_WIDTH),
        .AXI_ID_WIDTH_DEST(s2mm_axi.ID_WIDTH)
    ) i_s2mm_dma (
        .s_axi_aclk   (s2mm_axil.clk_i),
        .s_axi_aresetn(s2mm_axil.arstn_i),
        .s_axi_awvalid(s2mm_axil.awvalid),
        .s_axi_awaddr (s2mm_axil.awaddr),
        .s_axi_awready(s2mm_axil.awready),
        .s_axi_awprot (s2mm_axil.awprot),
        .s_axi_wvalid (s2mm_axil.wvalid),
        .s_axi_wdata  (s2mm_axil.wdata),
        .s_axi_wstrb  (s2mm_axil.wstrb),
        .s_axi_wready (s2mm_axil.wready),
        .s_axi_bvalid (s2mm_axil.bvalid),
        .s_axi_bresp  (s2mm_axil.bresp),
        .s_axi_bready (s2mm_axil.bready),
        .s_axi_arvalid(s2mm_axil.arvalid),
        .s_axi_araddr (s2mm_axil.araddr),
        .s_axi_arready(s2mm_axil.arready),
        .s_axi_arprot (s2mm_axil.arprot),
        .s_axi_rvalid (s2mm_axil.rvalid),
        .s_axi_rready (s2mm_axil.rready),
        .s_axi_rresp  (s2mm_axil.rresp),
        .s_axi_rdata  (s2mm_axil.rdata),

        .irq(s2mm_irq_o),

        .m_dest_axi_aclk   (s2mm_axi.clk_i),
        .m_dest_axi_aresetn(s2mm_axi.arstn_i),
        .m_dest_axi_awaddr (s2mm_axi.awaddr),
        .m_dest_axi_awlen  (s2mm_axi.awlen),
        .m_dest_axi_awsize (s2mm_axi.awsize),
        .m_dest_axi_awburst(s2mm_axi.awburst),
        .m_dest_axi_awprot (s2mm_axi.awprot),
        .m_dest_axi_awcache(s2mm_axi.awcache),
        .m_dest_axi_awvalid(s2mm_axi.awvalid),
        .m_dest_axi_awready(s2mm_axi.awready),
        .m_dest_axi_awid   (s2mm_axi.awid),
        .m_dest_axi_awlock (s2mm_axi.awlock),
        .m_dest_axi_wdata  (s2mm_axi.wdata),
        .m_dest_axi_wstrb  (s2mm_axi.wstrb),
        .m_dest_axi_wready (s2mm_axi.wready),
        .m_dest_axi_wvalid (s2mm_axi.wvalid),
        .m_dest_axi_wlast  (s2mm_axi.wlast),
        .m_dest_axi_wid    (s2mm_axi.wid),
        .m_dest_axi_bvalid (s2mm_axi.bvalid),
        .m_dest_axi_bresp  (s2mm_axi.bresp),
        .m_dest_axi_bready (s2mm_axi.bready),
        .m_dest_axi_bid    (s2mm_axi.bid),

        .m_src_axi_aclk   (),
        .m_src_axi_aresetn(),
        .m_src_axi_arready(),
        .m_src_axi_arvalid(),
        .m_src_axi_araddr (),
        .m_src_axi_arlen  (),
        .m_src_axi_arsize (),
        .m_src_axi_arburst(),
        .m_src_axi_arprot (),
        .m_src_axi_arcache(),
        .m_src_axi_arid   (),
        .m_src_axi_arlock (),
        .m_src_axi_rdata  (),
        .m_src_axi_rready (),
        .m_src_axi_rvalid (),
        .m_src_axi_rresp  (),
        .m_src_axi_rid    (),
        .m_src_axi_rlast  (),

        .s_axis_aclk    (s2mm_axis.clk_i),
        .s_axis_ready   (s2mm_axis.tready),
        .s_axis_valid   (s2mm_axis.tvalid),
        .s_axis_data    (s2mm_axis.tdata),
        .s_axis_strb    (s2mm_axis.tstrb),
        .s_axis_keep    (s2mm_axis.tkeep),
        .s_axis_user    (s2mm_axis.tuser),
        .s_axis_id      (s2mm_axis.tid),
        .s_axis_dest    (s2mm_axis.tdest),
        .s_axis_last    (s2mm_axis.tlast),
        .s_axis_xfer_req(),

        .m_axis_aclk    (),
        .m_axis_ready   (),
        .m_axis_valid   (),
        .m_axis_data    (),
        .m_axis_strb    (),
        .m_axis_keep    (),
        .m_axis_user    (),
        .m_axis_id      (),
        .m_axis_dest    (),
        .m_axis_last    (),
        .m_axis_xfer_req(),

        .fifo_wr_clk     (),
        .fifo_wr_en      (),
        .fifo_wr_din     (),
        .fifo_wr_overflow(),
        .fifo_wr_sync    (),
        .fifo_wr_xfer_req(),

        .fifo_rd_clk      (),
        .fifo_rd_en       (),
        .fifo_rd_valid    (),
        .fifo_rd_dout     (),
        .fifo_rd_underflow(),
        .fifo_rd_xfer_req (),

        .dest_diag_level_bursts()
    );

    axi_dmac #(
        .ID                     (0),
        .SYNC_TRANSFER_START    (0),
        .CYCLIC                 (1),
        .MAX_BYTES_PER_BURST    (128),
        .FIFO_SIZE              (8),
        .DISABLE_DEBUG_REGISTERS(0),
        .ENABLE_DIAGNOSTICS_IF  (0),
        .ALLOW_ASYM_MEM         (0),
        .CACHE_COHERENT_DEST    (0),

        .DMA_DATA_WIDTH_SRC   (mm2s_axi.DATA_WIDTH),
        .DMA_DATA_WIDTH_DEST  (mm2s_axi.DATA_WIDTH),
        .DMA_LENGTH_WIDTH     (24),
        .DMA_2D_TRANSFER      (0),
        .DMA_AXI_PROTOCOL_DEST(1),
        .DMA_AXI_PROTOCOL_SRC (1),
        .DMA_TYPE_DEST        (1),
        .DMA_TYPE_SRC         (1),
        .DMA_AXI_ADDR_WIDTH   (mm2s_axi.ADDR_WIDTH),
        .DMA_AXIS_ID_W        (mm2s_axis.ID_WIDTH),
        .DMA_AXIS_DEST_W      (mm2s_axis.DEST_WIDTH),

        .ASYNC_CLK_REQ_SRC (0),
        .ASYNC_CLK_SRC_DEST(ASYNC_MODE_EN),
        .ASYNC_CLK_DEST_REQ(ASYNC_MODE_EN),

        .AXI_SLICE_DEST   (0),
        .AXI_SLICE_SRC    (0),
        .AXI_ID_WIDTH_SRC (mm2s_axi.ID_WIDTH),
        .AXI_ID_WIDTH_DEST(mm2s_axi.ID_WIDTH)
    ) i_mm2s_dma (
        .s_axi_aclk   (mm2s_axil.clk_i),
        .s_axi_aresetn(mm2s_axil.arstn_i),
        .s_axi_awvalid(mm2s_axil.awvalid),
        .s_axi_awaddr (mm2s_axil.awaddr),
        .s_axi_awready(mm2s_axil.awready),
        .s_axi_awprot (mm2s_axil.awprot),
        .s_axi_wvalid (mm2s_axil.wvalid),
        .s_axi_wdata  (mm2s_axil.wdata),
        .s_axi_wstrb  (mm2s_axil.wstrb),
        .s_axi_wready (mm2s_axil.wready),
        .s_axi_bvalid (mm2s_axil.bvalid),
        .s_axi_bresp  (mm2s_axil.bresp),
        .s_axi_bready (mm2s_axil.bready),
        .s_axi_arvalid(mm2s_axil.arvalid),
        .s_axi_araddr (mm2s_axil.araddr),
        .s_axi_arready(mm2s_axil.arready),
        .s_axi_arprot (mm2s_axil.arprot),
        .s_axi_rvalid (mm2s_axil.rvalid),
        .s_axi_rready (mm2s_axil.rready),
        .s_axi_rresp  (mm2s_axil.rresp),
        .s_axi_rdata  (mm2s_axil.rdata),

        .irq(mm2s_irq_o),

        .m_dest_axi_aclk   (),
        .m_dest_axi_aresetn(),
        .m_dest_axi_awaddr (),
        .m_dest_axi_awlen  (),
        .m_dest_axi_awsize (),
        .m_dest_axi_awburst(),
        .m_dest_axi_awprot (),
        .m_dest_axi_awcache(),
        .m_dest_axi_awvalid(),
        .m_dest_axi_awready(),
        .m_dest_axi_awid   (),
        .m_dest_axi_awlock (),
        .m_dest_axi_wdata  (),
        .m_dest_axi_wstrb  (),
        .m_dest_axi_wready (),
        .m_dest_axi_wvalid (),
        .m_dest_axi_wlast  (),
        .m_dest_axi_wid    (),
        .m_dest_axi_bvalid (),
        .m_dest_axi_bresp  (),
        .m_dest_axi_bready (),
        .m_dest_axi_bid    (),

        .m_src_axi_aclk   (mm2s_axi.clk_i),
        .m_src_axi_aresetn(mm2s_axi.arstn_i),
        .m_src_axi_arready(mm2s_axi.arready),
        .m_src_axi_arvalid(mm2s_axi.arvalid),
        .m_src_axi_araddr (mm2s_axi.araddr),
        .m_src_axi_arlen  (mm2s_axi.arlen),
        .m_src_axi_arsize (mm2s_axi.arsize),
        .m_src_axi_arburst(mm2s_axi.arburst),
        .m_src_axi_arprot (mm2s_axi.arprot),
        .m_src_axi_arcache(mm2s_axi.arcache),
        .m_src_axi_arid   (mm2s_axi.arid),
        .m_src_axi_arlock (mm2s_axi.arlock),
        .m_src_axi_rdata  (mm2s_axi.rdata),
        .m_src_axi_rready (mm2s_axi.rready),
        .m_src_axi_rvalid (mm2s_axi.rvalid),
        .m_src_axi_rresp  (mm2s_axi.rresp),
        .m_src_axi_rid    (mm2s_axi.rid),
        .m_src_axi_rlast  (mm2s_axi.rlast),

        .s_axis_aclk    (),
        .s_axis_ready   (),
        .s_axis_valid   (),
        .s_axis_data    (),
        .s_axis_strb    (),
        .s_axis_keep    (),
        .s_axis_user    (),
        .s_axis_id      (),
        .s_axis_dest    (),
        .s_axis_last    (),
        .s_axis_xfer_req(),

        .m_axis_aclk    (mm2s_axis.clk_i),
        .m_axis_ready   (mm2s_axis.tready),
        .m_axis_valid   (mm2s_axis.tvalid),
        .m_axis_data    (mm2s_axis.tdata),
        .m_axis_strb    (mm2s_axis.tstrb),
        .m_axis_keep    (mm2s_axis.tkeep),
        .m_axis_user    (mm2s_axis.tuser),
        .m_axis_id      (mm2s_axis.tid),
        .m_axis_dest    (mm2s_axis.tdest),
        .m_axis_last    (mm2s_axis.tlast),
        .m_axis_xfer_req(),

        .fifo_wr_clk     (),
        .fifo_wr_en      (),
        .fifo_wr_din     (),
        .fifo_wr_overflow(),
        .fifo_wr_sync    (),
        .fifo_wr_xfer_req(),

        .fifo_rd_clk      (),
        .fifo_rd_en       (),
        .fifo_rd_valid    (),
        .fifo_rd_dout     (),
        .fifo_rd_underflow(),
        .fifo_rd_xfer_req (),

        .dest_diag_level_bursts()
    );

    if (ILA_EN) begin : g_ila
        axil_ila i_s2mm_ila (
            .clk    (s2mm_axil.clk_i),
            .probe0 (s2mm_axil.awvalid),
            .probe1 (s2mm_axil.awaddr),
            .probe2 (s2mm_axil.bresp),
            .probe3 (s2mm_axil.bvalid),
            .probe4 (s2mm_axil.bready),
            .probe5 (s2mm_axil.wdata),
            .probe6 (s2mm_axil.wvalid),
            .probe7 (s2mm_axil.wready),
            .probe8 (s2mm_axil.awready),
            .probe9 (s2mm_axil.rready),
            .probe10(s2mm_axil.araddr),
            .probe11(s2mm_axil.arvalid),
            .probe12(s2mm_axil.arready),
            .probe13(s2mm_axil.rresp),
            .probe14(s2mm_axil.rdata),
            .probe15(s2mm_axil.wstrb),
            .probe16(s2mm_axil.rvalid),
            .probe17(s2mm_axil.arprot),
            .probe18(s2mm_axil.awprot)
        );

        axil_ila i_mm2s_ila (
            .clk    (mm2s_axil.clk_i),
            .probe0 (mm2s_axil.awvalid),
            .probe1 (mm2s_axil.awaddr),
            .probe2 (mm2s_axil.bresp),
            .probe3 (mm2s_axil.bvalid),
            .probe4 (mm2s_axil.bready),
            .probe5 (mm2s_axil.wdata),
            .probe6 (mm2s_axil.wvalid),
            .probe7 (mm2s_axil.wready),
            .probe8 (mm2s_axil.awready),
            .probe9 (mm2s_axil.rready),
            .probe10(mm2s_axil.araddr),
            .probe11(mm2s_axil.arvalid),
            .probe12(mm2s_axil.arready),
            .probe13(mm2s_axil.rresp),
            .probe14(mm2s_axil.rdata),
            .probe15(mm2s_axil.wstrb),
            .probe16(mm2s_axil.rvalid),
            .probe17(mm2s_axil.arprot),
            .probe18(mm2s_axil.awprot)
        );
    end

endmodule
