module axi_dmac_wrap #(
    parameter bit ILA_EN       = 1,
    parameter bit ASYNC_EN_ADC = 1,
    parameter bit ASYNC_EN_DAC = 1
) (
    output logic adc_dma_irq_o,
    output logic dac_dma_irq_o,

    axis_if.slave  dac_axis,
    axis_if.master adc_axis,

    axil_if.slave adc_axil,
    axil_if.slave dac_axil,

    axi_if.master m_axi
);

    axi_dmac #(
        .ID                     (0),
        .SYNC_TRANSFER_START    (0),
        .CYCLIC                 (0),
        .MAX_BYTES_PER_BURST    (128),
        .FIFO_SIZE              (8),
        .DISABLE_DEBUG_REGISTERS(0),
        .ENABLE_DIAGNOSTICS_IF  (0),
        .ALLOW_ASYM_MEM         (0),
        .CACHE_COHERENT_DEST    (0),

        .DMA_DATA_WIDTH_SRC   (m_axi.DATA_WIDTH),
        .DMA_DATA_WIDTH_DEST  (m_axi.DATA_WIDTH),
        .DMA_LENGTH_WIDTH     (24),
        .DMA_2D_TRANSFER      (0),
        .DMA_AXI_PROTOCOL_DEST(1),
        .DMA_AXI_PROTOCOL_SRC (1),
        .DMA_TYPE_DEST        (1),
        .DMA_TYPE_SRC         (1),
        .DMA_AXI_ADDR_WIDTH   (m_axi.ADDR_WIDTH),
        .DMA_AXIS_ID_W        (adc_axis.ID_WIDTH),
        .DMA_AXIS_DEST_W      (adc_axis.DEST_WIDTH),

        .ASYNC_CLK_REQ_SRC (ASYNC_EN_ADC),
        .ASYNC_CLK_SRC_DEST(ASYNC_EN_ADC),
        .ASYNC_CLK_DEST_REQ(0),

        .AXI_SLICE_DEST   (0),
        .AXI_SLICE_SRC    (0),
        .AXI_ID_WIDTH_SRC (m_axi.ID_WIDTH),
        .AXI_ID_WIDTH_DEST(m_axi.ID_WIDTH)
    ) i_adc_dma (
        .s_axi_aclk   (adc_axil.clk_i),
        .s_axi_aresetn(adc_axil.arstn_i),
        .s_axi_awvalid(adc_axil.awvalid),
        .s_axi_awaddr (adc_axil.awaddr),
        .s_axi_awready(adc_axil.awready),
        .s_axi_awprot (adc_axil.awprot),
        .s_axi_wvalid (adc_axil.wvalid),
        .s_axi_wdata  (adc_axil.wdata),
        .s_axi_wstrb  (adc_axil.wstrb),
        .s_axi_wready (adc_axil.wready),
        .s_axi_bvalid (adc_axil.bvalid),
        .s_axi_bresp  (adc_axil.bresp),
        .s_axi_bready (adc_axil.bready),
        .s_axi_arvalid(adc_axil.arvalid),
        .s_axi_araddr (adc_axil.araddr),
        .s_axi_arready(adc_axil.arready),
        .s_axi_arprot (adc_axil.arprot),
        .s_axi_rvalid (adc_axil.rvalid),
        .s_axi_rready (adc_axil.rready),
        .s_axi_rresp  (adc_axil.rresp),
        .s_axi_rdata  (adc_axil.rdata),

        .irq(adc_dma_irq_o),

        .m_dest_axi_aclk   (m_axi.clk_i),
        .m_dest_axi_aresetn(m_axi.arstn_i),
        .m_dest_axi_awaddr (m_axi.awaddr),
        .m_dest_axi_awlen  (m_axi.awlen),
        .m_dest_axi_awsize (m_axi.awsize),
        .m_dest_axi_awburst(m_axi.awburst),
        .m_dest_axi_awprot (m_axi.awprot),
        .m_dest_axi_awcache(m_axi.awcache),
        .m_dest_axi_awvalid(m_axi.awvalid),
        .m_dest_axi_awready(m_axi.awready),
        .m_dest_axi_awid   (m_axi.awid),
        .m_dest_axi_awlock (m_axi.awlock),
        .m_dest_axi_wdata  (m_axi.wdata),
        .m_dest_axi_wstrb  (m_axi.wstrb),
        .m_dest_axi_wready (m_axi.wready),
        .m_dest_axi_wvalid (m_axi.wvalid),
        .m_dest_axi_wlast  (m_axi.wlast),
        .m_dest_axi_wid    (m_axi.wid),
        .m_dest_axi_bvalid (m_axi.bvalid),
        .m_dest_axi_bresp  (m_axi.bresp),
        .m_dest_axi_bready (m_axi.bready),
        .m_dest_axi_bid    (m_axi.bid),

        .m_src_axi_aclk   (),
        .m_src_axi_aresetn(),
        .m_src_axi_arready(),
        .m_src_axi_arvalid(),
        .m_src_axi_araddr (),
        .m_src_axi_arlen  (),
        .m_src_axi_arsize (),
        .m_src_axi_arburst(),
        .m_src_axi_arprot (),
        .m_src_axi_arcache(),
        .m_src_axi_arid   (),
        .m_src_axi_arlock (),
        .m_src_axi_rdata  (),
        .m_src_axi_rready (),
        .m_src_axi_rvalid (),
        .m_src_axi_rresp  (),
        .m_src_axi_rid    (),
        .m_src_axi_rlast  (),

        .s_axis_aclk    (adc_axis.clk_i),
        .s_axis_ready   (adc_axis.tready),
        .s_axis_valid   (adc_axis.tvalid),
        .s_axis_data    (adc_axis.tdata),
        .s_axis_strb    (adc_axis.tstrb),
        .s_axis_keep    (adc_axis.tkeep),
        .s_axis_user    (adc_axis.tuser),
        .s_axis_id      (adc_axis.tid),
        .s_axis_dest    (adc_axis.tdest),
        .s_axis_last    (adc_axis.tlast),
        .s_axis_xfer_req(),

        .m_axis_aclk    (),
        .m_axis_ready   (),
        .m_axis_valid   (),
        .m_axis_data    (),
        .m_axis_strb    (),
        .m_axis_keep    (),
        .m_axis_user    (),
        .m_axis_id      (),
        .m_axis_dest    (),
        .m_axis_last    (),
        .m_axis_xfer_req(),

        .fifo_wr_clk     (),
        .fifo_wr_en      (),
        .fifo_wr_din     (),
        .fifo_wr_overflow(),
        .fifo_wr_sync    (),
        .fifo_wr_xfer_req(),

        .fifo_rd_clk      (),
        .fifo_rd_en       (),
        .fifo_rd_valid    (),
        .fifo_rd_dout     (),
        .fifo_rd_underflow(),
        .fifo_rd_xfer_req (),

        .dest_diag_level_bursts()
    );

    axi_dmac #(
        .ID                     (0),
        .SYNC_TRANSFER_START    (0),
        .CYCLIC                 (1),
        .MAX_BYTES_PER_BURST    (128),
        .FIFO_SIZE              (8),
        .DISABLE_DEBUG_REGISTERS(0),
        .ENABLE_DIAGNOSTICS_IF  (0),
        .ALLOW_ASYM_MEM         (0),
        .CACHE_COHERENT_DEST    (0),

        .DMA_DATA_WIDTH_SRC   (m_axi.DATA_WIDTH),
        .DMA_DATA_WIDTH_DEST  (m_axi.DATA_WIDTH),
        .DMA_LENGTH_WIDTH     (24),
        .DMA_2D_TRANSFER      (0),
        .DMA_AXI_PROTOCOL_DEST(1),
        .DMA_AXI_PROTOCOL_SRC (1),
        .DMA_TYPE_DEST        (1),
        .DMA_TYPE_SRC         (1),
        .DMA_AXI_ADDR_WIDTH   (m_axi.ADDR_WIDTH),
        .DMA_AXIS_ID_W        (dac_axis.ID_WIDTH),
        .DMA_AXIS_DEST_W      (dac_axis.DEST_WIDTH),

        .ASYNC_CLK_REQ_SRC (0),
        .ASYNC_CLK_SRC_DEST(ASYNC_EN_DAC),
        .ASYNC_CLK_DEST_REQ(ASYNC_EN_DAC),

        .AXI_SLICE_DEST   (0),
        .AXI_SLICE_SRC    (0),
        .AXI_ID_WIDTH_SRC (m_axi.ID_WIDTH),
        .AXI_ID_WIDTH_DEST(m_axi.ID_WIDTH)
    ) i_dac_dma (
        .s_axi_aclk   (dac_axil.clk_i),
        .s_axi_aresetn(dac_axil.arstn_i),
        .s_axi_awvalid(dac_axil.awvalid),
        .s_axi_awaddr (dac_axil.awaddr),
        .s_axi_awready(dac_axil.awready),
        .s_axi_awprot (dac_axil.awprot),
        .s_axi_wvalid (dac_axil.wvalid),
        .s_axi_wdata  (dac_axil.wdata),
        .s_axi_wstrb  (dac_axil.wstrb),
        .s_axi_wready (dac_axil.wready),
        .s_axi_bvalid (dac_axil.bvalid),
        .s_axi_bresp  (dac_axil.bresp),
        .s_axi_bready (dac_axil.bready),
        .s_axi_arvalid(dac_axil.arvalid),
        .s_axi_araddr (dac_axil.araddr),
        .s_axi_arready(dac_axil.arready),
        .s_axi_arprot (dac_axil.arprot),
        .s_axi_rvalid (dac_axil.rvalid),
        .s_axi_rready (dac_axil.rready),
        .s_axi_rresp  (dac_axil.rresp),
        .s_axi_rdata  (dac_axil.rdata),

        .irq(dac_dma_irq_o),

        .m_dest_axi_aclk   (),
        .m_dest_axi_aresetn(),
        .m_dest_axi_awaddr (),
        .m_dest_axi_awlen  (),
        .m_dest_axi_awsize (),
        .m_dest_axi_awburst(),
        .m_dest_axi_awprot (),
        .m_dest_axi_awcache(),
        .m_dest_axi_awvalid(),
        .m_dest_axi_awready(),
        .m_dest_axi_awid   (),
        .m_dest_axi_awlock (),
        .m_dest_axi_wdata  (),
        .m_dest_axi_wstrb  (),
        .m_dest_axi_wready (),
        .m_dest_axi_wvalid (),
        .m_dest_axi_wlast  (),
        .m_dest_axi_wid    (),
        .m_dest_axi_bvalid (),
        .m_dest_axi_bresp  (),
        .m_dest_axi_bready (),
        .m_dest_axi_bid    (),

        .m_src_axi_aclk   (m_axi.clk_i),
        .m_src_axi_aresetn(m_axi.arstn_i),
        .m_src_axi_arready(m_axi.arready),
        .m_src_axi_arvalid(m_axi.arvalid),
        .m_src_axi_araddr (m_axi.araddr),
        .m_src_axi_arlen  (m_axi.arlen),
        .m_src_axi_arsize (m_axi.arsize),
        .m_src_axi_arburst(m_axi.arburst),
        .m_src_axi_arprot (m_axi.arprot),
        .m_src_axi_arcache(m_axi.arcache),
        .m_src_axi_arid   (m_axi.arid),
        .m_src_axi_arlock (m_axi.arlock),
        .m_src_axi_rdata  (m_axi.rdata),
        .m_src_axi_rready (m_axi.rready),
        .m_src_axi_rvalid (m_axi.rvalid),
        .m_src_axi_rresp  (m_axi.rresp),
        .m_src_axi_rid    (m_axi.rid),
        .m_src_axi_rlast  (m_axi.rlast),

        .s_axis_aclk    (),
        .s_axis_ready   (),
        .s_axis_valid   (),
        .s_axis_data    (),
        .s_axis_strb    (),
        .s_axis_keep    (),
        .s_axis_user    (),
        .s_axis_id      (),
        .s_axis_dest    (),
        .s_axis_last    (),
        .s_axis_xfer_req(),

        .m_axis_aclk    (dac_axis.clk_i),
        .m_axis_ready   (dac_axis.tready),
        .m_axis_valid   (dac_axis.tvalid),
        .m_axis_data    (dac_axis.tdata),
        .m_axis_strb    (dac_axis.tstrb),
        .m_axis_keep    (dac_axis.tkeep),
        .m_axis_user    (dac_axis.tuser),
        .m_axis_id      (dac_axis.tid),
        .m_axis_dest    (dac_axis.tdest),
        .m_axis_last    (dac_axis.tlast),
        .m_axis_xfer_req(),

        .fifo_wr_clk     (),
        .fifo_wr_en      (),
        .fifo_wr_din     (),
        .fifo_wr_overflow(),
        .fifo_wr_sync    (),
        .fifo_wr_xfer_req(),

        .fifo_rd_clk      (),
        .fifo_rd_en       (),
        .fifo_rd_valid    (),
        .fifo_rd_dout     (),
        .fifo_rd_underflow(),
        .fifo_rd_xfer_req (),

        .dest_diag_level_bursts()
    );

    if (ILA_EN) begin : g_ila
        axil_ila i_adc_ila (
            .clk    (adc_axil.clk_i),
            .probe0 (adc_axil.awvalid),
            .probe1 (adc_axil.awaddr),
            .probe2 (adc_axil.bresp),
            .probe3 (adc_axil.bvalid),
            .probe4 (adc_axil.bready),
            .probe5 (adc_axil.wdata),
            .probe6 (adc_axil.wvalid),
            .probe7 (adc_axil.wready),
            .probe8 (adc_axil.awready),
            .probe9 (adc_axil.rready),
            .probe10(adc_axil.araddr),
            .probe11(adc_axil.arvalid),
            .probe12(adc_axil.arready),
            .probe13(adc_axil.rresp),
            .probe14(adc_axil.rdata),
            .probe15(adc_axil.wstrb),
            .probe16(adc_axil.rvalid),
            .probe17(adc_axil.arprot),
            .probe18(adc_axil.awprot)
        );

        axil_ila i_adc_ila (
            .clk    (dac_axil.clk_i),
            .probe0 (dac_axil.awvalid),
            .probe1 (dac_axil.awaddr),
            .probe2 (dac_axil.bresp),
            .probe3 (dac_axil.bvalid),
            .probe4 (dac_axil.bready),
            .probe5 (dac_axil.wdata),
            .probe6 (dac_axil.wvalid),
            .probe7 (dac_axil.wready),
            .probe8 (dac_axil.awready),
            .probe9 (dac_axil.rready),
            .probe10(dac_axil.araddr),
            .probe11(dac_axil.arvalid),
            .probe12(dac_axil.arready),
            .probe13(dac_axil.rresp),
            .probe14(dac_axil.rdata),
            .probe15(dac_axil.wstrb),
            .probe16(dac_axil.rvalid),
            .probe17(dac_axil.arprot),
            .probe18(dac_axil.awprot)
        );
    end

endmodule
