module bd_top (
    inout [14:0] ddr_addr,
    inout [ 2:0] ddr_ba,
    inout        ddr_cas_n,
    inout        ddr_ck_n,
    inout        ddr_ck_p,
    inout        ddr_cke,
    inout        ddr_cs_n,
    inout [ 3:0] ddr_dm,
    inout [31:0] ddr_dq,
    inout [ 3:0] ddr_dqs_n,
    inout [ 3:0] ddr_dqs_p,
    inout        ddr_odt,
    inout        ddr_ras_n,
    inout        ddr_reset_n,
    inout        ddr_we_n,

    inout        fixed_io_ddr_vrn,
    inout        fixed_io_ddr_vrp,
    inout [53:0] fixed_io_mio,
    inout        fixed_io_ps_clk,
    inout        fixed_io_ps_porb,
    inout        fixed_io_ps_srstb,

    input  logic i2c_scl_i,
    output logic i2c_scl_o,
    output logic i2c_scl_t,
    input  logic i2c_sda_i,
    output logic i2c_sda_o,
    output logic i2c_sda_t,

    input  logic gpio_i,
    output logic gpio_o,
    output logic gpio_t,

    output logic ps_spi_csn_o,
    output logic ps_spi_clk_o,
    output logic ps_spi_mosi_o,
    input  logic ps_spi_miso_i,

    output logic pl_spi_clk_o,
    output logic pl_spi_mosi_o,
    input  logic pl_spi_miso_i,

    input logic pps_irq_i,
    input logic s2mm_irq_i,
    input logic mm2s_irq_i,

    output logic ps_clk1_o,
    output logic ps_clk2_o,
    output logic ps_arstn_o,

    axil_if.master ad_axil,
    axil_if.master s2mm_axil,
    axil_if.master mm2s_axil,
    axil_if.master ext_axil,
    axi_if.master  hp_axi

);

    libre_bd i_libre_bd (
        .DDR_0_addr   (ddr_addr),
        .DDR_0_ba     (ddr_ba),
        .DDR_0_cas_n  (ddr_cas_n),
        .DDR_0_ck_n   (ddr_ck_n),
        .DDR_0_ck_p   (ddr_ck_p),
        .DDR_0_cke    (ddr_cke),
        .DDR_0_cs_n   (ddr_cs_n),
        .DDR_0_dm     (ddr_dm),
        .DDR_0_dq     (ddr_dq),
        .DDR_0_dqs_n  (ddr_dqs_n),
        .DDR_0_dqs_p  (ddr_dqs_p),
        .DDR_0_odt    (ddr_odt),
        .DDR_0_ras_n  (ddr_ras_n),
        .DDR_0_reset_n(ddr_reset_n),
        .DDR_0_we_n   (ddr_we_n),

        .FCLK_CLK0_0    (ps_clk1_o),
        .FCLK_CLK1_0    (ps_clk2_o),
        .FCLK_RESET0_N_0(ps_arstn_o),

        .FIXED_IO_0_ddr_vrn (fixed_io_ddr_vrn),
        .FIXED_IO_0_ddr_vrp (fixed_io_ddr_vrp),
        .FIXED_IO_0_mio     (fixed_io_mio),
        .FIXED_IO_0_ps_clk  (fixed_io_ps_clk),
        .FIXED_IO_0_ps_porb (fixed_io_ps_porb),
        .FIXED_IO_0_ps_srstb(fixed_io_ps_srstb),

        .GPIO_0_0_tri_i(gpio_i),
        .GPIO_0_0_tri_o(gpio_o),
        .GPIO_0_0_tri_t(gpio_t),

        .IIC_0_scl_i(i2c_scl_i),
        .IIC_0_scl_o(i2c_scl_o),
        .IIC_0_scl_t(i2c_scl_t),
        .IIC_0_sda_i(i2c_sda_i),
        .IIC_0_sda_o(i2c_sda_o),
        .IIC_0_sda_t(i2c_sda_t),

        .AXI_AD9361_0_araddr (ad_axil.araddr),
        .AXI_AD9361_0_arprot (ad_axil.arprot),
        .AXI_AD9361_0_arready(ad_axil.arready),
        .AXI_AD9361_0_arvalid(ad_axil.arvalid),
        .AXI_AD9361_0_awaddr (ad_axil.awaddr),
        .AXI_AD9361_0_awprot (ad_axil.awprot),
        .AXI_AD9361_0_awready(ad_axil.awready),
        .AXI_AD9361_0_awvalid(ad_axil.awvalid),
        .AXI_AD9361_0_bready (ad_axil.bready),
        .AXI_AD9361_0_bresp  (ad_axil.bresp),
        .AXI_AD9361_0_bvalid (ad_axil.bvalid),
        .AXI_AD9361_0_rdata  (ad_axil.rdata),
        .AXI_AD9361_0_rready (ad_axil.rready),
        .AXI_AD9361_0_rresp  (ad_axil.rresp),
        .AXI_AD9361_0_rvalid (ad_axil.rvalid),
        .AXI_AD9361_0_wdata  (ad_axil.wdata),
        .AXI_AD9361_0_wready (ad_axil.wready),
        .AXI_AD9361_0_wstrb  (ad_axil.wstrb),
        .AXI_AD9361_0_wvalid (ad_axil.wvalid),

        .AXI_DMAC_0_araddr (s2mm_axil.araddr),
        .AXI_DMAC_0_arprot (s2mm_axil.arprot),
        .AXI_DMAC_0_arready(s2mm_axil.arready),
        .AXI_DMAC_0_arvalid(s2mm_axil.arvalid),
        .AXI_DMAC_0_awaddr (s2mm_axil.awaddr),
        .AXI_DMAC_0_awprot (s2mm_axil.awprot),
        .AXI_DMAC_0_awready(s2mm_axil.awready),
        .AXI_DMAC_0_awvalid(s2mm_axil.awvalid),
        .AXI_DMAC_0_bready (s2mm_axil.bready),
        .AXI_DMAC_0_bresp  (s2mm_axil.bresp),
        .AXI_DMAC_0_bvalid (s2mm_axil.bvalid),
        .AXI_DMAC_0_rdata  (s2mm_axil.rdata),
        .AXI_DMAC_0_rready (s2mm_axil.rready),
        .AXI_DMAC_0_rresp  (s2mm_axil.rresp),
        .AXI_DMAC_0_rvalid (s2mm_axil.rvalid),
        .AXI_DMAC_0_wdata  (s2mm_axil.wdata),
        .AXI_DMAC_0_wready (s2mm_axil.wready),
        .AXI_DMAC_0_wstrb  (s2mm_axil.wstrb),
        .AXI_DMAC_0_wvalid (s2mm_axil.wvalid),

        .AXI_DMAC_1_araddr (mm2s_axil.araddr),
        .AXI_DMAC_1_arprot (mm2s_axil.arprot),
        .AXI_DMAC_1_arready(mm2s_axil.arready),
        .AXI_DMAC_1_arvalid(mm2s_axil.arvalid),
        .AXI_DMAC_1_awaddr (mm2s_axil.awaddr),
        .AXI_DMAC_1_awprot (mm2s_axil.awprot),
        .AXI_DMAC_1_awready(mm2s_axil.awready),
        .AXI_DMAC_1_awvalid(mm2s_axil.awvalid),
        .AXI_DMAC_1_bready (mm2s_axil.bready),
        .AXI_DMAC_1_bresp  (mm2s_axil.bresp),
        .AXI_DMAC_1_bvalid (mm2s_axil.bvalid),
        .AXI_DMAC_1_rdata  (mm2s_axil.rdata),
        .AXI_DMAC_1_rready (mm2s_axil.rready),
        .AXI_DMAC_1_rresp  (mm2s_axil.rresp),
        .AXI_DMAC_1_rvalid (mm2s_axil.rvalid),
        .AXI_DMAC_1_wdata  (mm2s_axil.wdata),
        .AXI_DMAC_1_wready (mm2s_axil.wready),
        .AXI_DMAC_1_wstrb  (mm2s_axil.wstrb),
        .AXI_DMAC_1_wvalid (mm2s_axil.wvalid),

        .M05_AXI_0_araddr (ext_axil.araddr),
        .M05_AXI_0_arprot (ext_axil.arprot),
        .M05_AXI_0_arready(ext_axil.arready),
        .M05_AXI_0_arvalid(ext_axil.arvalid),
        .M05_AXI_0_awaddr (ext_axil.awaddr),
        .M05_AXI_0_awprot (ext_axil.awprot),
        .M05_AXI_0_awready(ext_axil.awready),
        .M05_AXI_0_awvalid(ext_axil.awvalid),
        .M05_AXI_0_bready (ext_axil.bready),
        .M05_AXI_0_bresp  (ext_axil.bresp),
        .M05_AXI_0_bvalid (ext_axil.bvalid),
        .M05_AXI_0_rdata  (ext_axil.rdata),
        .M05_AXI_0_rready (ext_axil.rready),
        .M05_AXI_0_rresp  (ext_axil.rresp),
        .M05_AXI_0_rvalid (ext_axil.rvalid),
        .M05_AXI_0_wdata  (ext_axil.wdata),
        .M05_AXI_0_wready (ext_axil.wready),
        .M05_AXI_0_wstrb  (ext_axil.wstrb),
        .M05_AXI_0_wvalid (ext_axil.wvalid),

        .SPI_0_0_io0_i('0),
        .SPI_0_0_io0_o(ps_spi_mosi_o),
        .SPI_0_0_io0_t(),
        .SPI_0_0_io1_i(ps_spi_miso_i),
        .SPI_0_0_io1_o(),
        .SPI_0_0_io1_t(),
        .SPI_0_0_sck_i('0),
        .SPI_0_0_sck_o(ps_spi_clk_o),
        .SPI_0_0_sck_t(),
        .SPI_0_0_ss1_o(),
        .SPI_0_0_ss2_o(),
        .SPI_0_0_ss_i ('1),
        .SPI_0_0_ss_o (ps_spi_csn_o),
        .SPI_0_0_ss_t (),

        .SPI_0_1_io0_i('0),
        .SPI_0_1_io0_o(pl_spi_mosi_o),
        .SPI_0_1_io0_t(),
        .SPI_0_1_io1_i(pl_spi_miso_i),
        .SPI_0_1_io1_o(),
        .SPI_0_1_io1_t(),
        .SPI_0_1_sck_i('0),
        .SPI_0_1_sck_o(pl_spi_clk_o),
        .SPI_0_1_sck_t(),
        .SPI_0_1_ss_i ('1),
        .SPI_0_1_ss_o (),
        .SPI_0_1_ss_t (),

        .S_AXI_HP1_0_araddr (hp_axi.araddr),
        .S_AXI_HP1_0_arburst(hp_axi.arburst),
        .S_AXI_HP1_0_arcache(hp_axi.arcache),
        .S_AXI_HP1_0_arid   (hp_axi.arid),
        .S_AXI_HP1_0_arlen  (hp_axi.arlen),
        .S_AXI_HP1_0_arlock (hp_axi.arlock),
        .S_AXI_HP1_0_arprot (hp_axi.arprot),
        .S_AXI_HP1_0_arqos  (hp_axi.arqos),
        .S_AXI_HP1_0_arready(hp_axi.arready),
        .S_AXI_HP1_0_arsize (hp_axi.arsize),
        .S_AXI_HP1_0_arvalid(hp_axi.arvalid),
        .S_AXI_HP1_0_rdata  (hp_axi.rdata),
        .S_AXI_HP1_0_rid    (hp_axi.rid),
        .S_AXI_HP1_0_rlast  (hp_axi.rlast),
        .S_AXI_HP1_0_rready (hp_axi.rready),
        .S_AXI_HP1_0_rresp  (hp_axi.rresp),
        .S_AXI_HP1_0_rvalid (hp_axi.rvalid),
        .S_AXI_HP1_0_awaddr (hp_axi.awaddr),
        .S_AXI_HP1_0_awburst(hp_axi.awburst),
        .S_AXI_HP1_0_awcache(hp_axi.awcache),
        .S_AXI_HP1_0_awid   (hp_axi.awid),
        .S_AXI_HP1_0_awlen  (hp_axi.awlen),
        .S_AXI_HP1_0_awlock (hp_axi.awlock),
        .S_AXI_HP1_0_awprot (hp_axi.awprot),
        .S_AXI_HP1_0_awqos  (hp_axi.awqos),
        .S_AXI_HP1_0_awready(hp_axi.awready),
        .S_AXI_HP1_0_awsize (hp_axi.awsize),
        .S_AXI_HP1_0_awvalid(hp_axi.awvalid),
        .S_AXI_HP1_0_bid    (hp_axi.bid),
        .S_AXI_HP1_0_bready (hp_axi.bready),
        .S_AXI_HP1_0_bresp  (hp_axi.bresp),
        .S_AXI_HP1_0_bvalid (hp_axi.bvalid),
        .S_AXI_HP1_0_wdata  (hp_axi.wdata),
        .S_AXI_HP1_0_wid    (hp_axi.wid),
        .S_AXI_HP1_0_wlast  (hp_axi.wlast),
        .S_AXI_HP1_0_wready (hp_axi.wready),
        .S_AXI_HP1_0_wstrb  (hp_axi.wstrb),
        .S_AXI_HP1_0_wvalid (hp_axi.wvalid),

        .s2mm_irq(s2mm_irq_i),
        .mm2s_irq(mm2s_irq_i),
        .pps_irq (pps_irq_i)
    );

endmodule
